-- 开发期补齐全部现存表字段中文注释；仅对当前有效列 COMMENT，已删除/重命名列不再写入。
COMMENT ON TABLE delivery_capabilities IS 'delivery_capabilities表';
COMMENT ON COLUMN delivery_capabilities.channel IS 'delivery_capabilities channel';
COMMENT ON COLUMN delivery_capabilities.config IS '配置 JSON';
COMMENT ON COLUMN delivery_capabilities.created_at IS '创建时间';
COMMENT ON COLUMN delivery_capabilities.id IS '主键';
COMMENT ON COLUMN delivery_capabilities.name IS '名称';
COMMENT ON COLUMN delivery_capabilities.requires_approval IS 'delivery_capabilities requires approval';
COMMENT ON COLUMN delivery_capabilities.risk_level IS '风险等级';
COMMENT ON COLUMN delivery_capabilities.status IS '状态';
COMMENT ON COLUMN delivery_capabilities.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN delivery_capabilities.updated_at IS '更新时间';
COMMENT ON COLUMN delivery_capabilities.version IS '版本号';
COMMENT ON TABLE delivery_records IS 'delivery_records表';
COMMENT ON COLUMN delivery_records.capability_id IS '系统能力 ID';
COMMENT ON COLUMN delivery_records.completed_at IS '完成时间';
COMMENT ON COLUMN delivery_records.created_at IS '创建时间';
COMMENT ON COLUMN delivery_records.created_by IS '创建人用户 ID';
COMMENT ON COLUMN delivery_records.delivery_type IS 'delivery_records delivery type';
COMMENT ON COLUMN delivery_records.error_code IS '错误码';
COMMENT ON COLUMN delivery_records.error_message IS '错误信息';
COMMENT ON COLUMN delivery_records.id IS '主键';
COMMENT ON COLUMN delivery_records.node_run_id IS '节点运行记录 ID';
COMMENT ON COLUMN delivery_records.payload IS '载荷 JSON';
COMMENT ON COLUMN delivery_records.result_snapshot IS 'delivery_records result snapshot';
COMMENT ON COLUMN delivery_records.run_id IS '工作流运行实例 ID';
COMMENT ON COLUMN delivery_records.status IS '状态';
COMMENT ON COLUMN delivery_records.target IS 'delivery_records target';
COMMENT ON COLUMN delivery_records.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN delivery_records.title IS 'delivery_records title';
COMMENT ON COLUMN delivery_records.workflow_id IS '工作流定义 ID';
COMMENT ON COLUMN delivery_records.workflow_version_id IS '工作流发布版本 ID';
COMMENT ON TABLE departments IS '部门表';
COMMENT ON COLUMN departments.code IS '编码';
COMMENT ON COLUMN departments.created_at IS '创建时间';
COMMENT ON COLUMN departments.id IS '主键';
COMMENT ON COLUMN departments.name IS '名称';
COMMENT ON COLUMN departments.parent_id IS '部门 parent id';
COMMENT ON COLUMN departments.sort_order IS '部门 sort order';
COMMENT ON COLUMN departments.status IS '状态';
COMMENT ON COLUMN departments.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN departments.updated_at IS '更新时间';
COMMENT ON TABLE mcp_call_logs IS 'mcp_call_logs表';
COMMENT ON COLUMN mcp_call_logs.capability_code IS 'mcp_call_logs capability code';
COMMENT ON COLUMN mcp_call_logs.capability_id IS '系统能力 ID';
COMMENT ON COLUMN mcp_call_logs.completed_at IS '完成时间';
COMMENT ON COLUMN mcp_call_logs.created_at IS '创建时间';
COMMENT ON COLUMN mcp_call_logs.error_code IS '错误码';
COMMENT ON COLUMN mcp_call_logs.error_message IS '错误信息';
COMMENT ON COLUMN mcp_call_logs.id IS '主键';
COMMENT ON COLUMN mcp_call_logs.latency_ms IS 'mcp_call_logs latency ms';
COMMENT ON COLUMN mcp_call_logs.node_run_id IS '节点运行记录 ID';
COMMENT ON COLUMN mcp_call_logs.request_payload IS 'mcp_call_logs request payload';
COMMENT ON COLUMN mcp_call_logs.response_payload IS 'mcp_call_logs response payload';
COMMENT ON COLUMN mcp_call_logs.run_id IS '工作流运行实例 ID';
COMMENT ON COLUMN mcp_call_logs.status IS '状态';
COMMENT ON COLUMN mcp_call_logs.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN mcp_call_logs.tool_name IS 'mcp_call_logs tool name';
COMMENT ON COLUMN mcp_call_logs.workflow_id IS '工作流定义 ID';
COMMENT ON COLUMN mcp_call_logs.workflow_version_id IS '工作流发布版本 ID';
COMMENT ON TABLE model_call_logs IS 'model_call_logs表';
COMMENT ON COLUMN model_call_logs.completed_at IS '完成时间';
COMMENT ON COLUMN model_call_logs.created_at IS '创建时间';
COMMENT ON COLUMN model_call_logs.error_code IS '错误码';
COMMENT ON COLUMN model_call_logs.error_message IS '错误信息';
COMMENT ON COLUMN model_call_logs.id IS '主键';
COMMENT ON COLUMN model_call_logs.latency_ms IS 'model_call_logs latency ms';
COMMENT ON COLUMN model_call_logs.model_name IS 'model_call_logs model name';
COMMENT ON COLUMN model_call_logs.node_run_id IS '节点运行记录 ID';
COMMENT ON COLUMN model_call_logs.prompt_snapshot IS 'model_call_logs prompt snapshot';
COMMENT ON COLUMN model_call_logs.provider_id IS '模型供应商 ID';
COMMENT ON COLUMN model_call_logs.provider_type IS 'model_call_logs provider type';
COMMENT ON COLUMN model_call_logs.response_snapshot IS 'model_call_logs response snapshot';
COMMENT ON COLUMN model_call_logs.run_id IS '工作流运行实例 ID';
COMMENT ON COLUMN model_call_logs.status IS '状态';
COMMENT ON COLUMN model_call_logs.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN model_call_logs.token_usage IS 'model_call_logs token usage';
COMMENT ON COLUMN model_call_logs.workflow_id IS '工作流定义 ID';
COMMENT ON COLUMN model_call_logs.workflow_version_id IS '工作流发布版本 ID';
COMMENT ON TABLE model_provider_types IS 'model_provider_types表';
COMMENT ON COLUMN model_provider_types.auth_scheme IS 'model_provider_types auth scheme';
COMMENT ON COLUMN model_provider_types.code IS '编码';
COMMENT ON COLUMN model_provider_types.created_at IS '创建时间';
COMMENT ON COLUMN model_provider_types.default_base_url IS 'model_provider_types default base url';
COMMENT ON COLUMN model_provider_types.description IS '描述';
COMMENT ON COLUMN model_provider_types.id IS '主键';
COMMENT ON COLUMN model_provider_types.model_list_endpoint IS 'model_provider_types model list endpoint';
COMMENT ON COLUMN model_provider_types.name IS '名称';
COMMENT ON COLUMN model_provider_types.settings IS 'model_provider_types settings';
COMMENT ON COLUMN model_provider_types.status IS '状态';
COMMENT ON COLUMN model_provider_types.updated_at IS '更新时间';
COMMENT ON TABLE model_providers IS '模型供应商表';
COMMENT ON COLUMN model_providers.base_url IS '模型供应商 base url';
COMMENT ON COLUMN model_providers.connectivity_status IS '模型供应商 connectivity status';
COMMENT ON COLUMN model_providers.created_at IS '创建时间';
COMMENT ON COLUMN model_providers.credential_ref IS '模型供应商 credential ref';
COMMENT ON COLUMN model_providers.default_model IS '模型供应商 default model';
COMMENT ON COLUMN model_providers.id IS '主键';
COMMENT ON COLUMN model_providers.name IS '名称';
COMMENT ON COLUMN model_providers.provider_type IS '模型供应商 provider type';
COMMENT ON COLUMN model_providers.settings IS '模型供应商 settings';
COMMENT ON COLUMN model_providers.status IS '状态';
COMMENT ON COLUMN model_providers.updated_at IS '更新时间';
COMMENT ON TABLE page_grants IS 'page_grants表';
COMMENT ON COLUMN page_grants.created_at IS '创建时间';
COMMENT ON COLUMN page_grants.grant_group_id IS '分配卡片分组 ID';
COMMENT ON COLUMN page_grants.grant_group_name IS '分配卡片名称';
COMMENT ON COLUMN page_grants.id IS '主键';
COMMENT ON COLUMN page_grants.page_key IS '页签键';
COMMENT ON COLUMN page_grants.principal_id IS '授权主体 ID';
COMMENT ON COLUMN page_grants.principal_type IS '授权主体类型';
COMMENT ON COLUMN page_grants.tenant_id IS '所属租户 ID';
COMMENT ON TABLE permission_policies IS 'permission_policies表';
COMMENT ON COLUMN permission_policies.actions IS 'permission_policies actions';
COMMENT ON COLUMN permission_policies.created_at IS '创建时间';
COMMENT ON COLUMN permission_policies.effect IS 'permission_policies effect';
COMMENT ON COLUMN permission_policies.id IS '主键';
COMMENT ON COLUMN permission_policies.resource_type IS '资源类型';
COMMENT ON COLUMN permission_policies.role_id IS '角色 ID';
COMMENT ON COLUMN permission_policies.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN permission_policies.updated_at IS '更新时间';
COMMENT ON TABLE prompt_templates IS 'prompt_templates表';
COMMENT ON COLUMN prompt_templates.category IS 'prompt_templates category';
COMMENT ON COLUMN prompt_templates.content IS 'prompt_templates content';
COMMENT ON COLUMN prompt_templates.created_at IS '创建时间';
COMMENT ON COLUMN prompt_templates.created_by IS '创建人用户 ID';
COMMENT ON COLUMN prompt_templates.id IS '主键';
COMMENT ON COLUMN prompt_templates.name IS '名称';
COMMENT ON COLUMN prompt_templates.status IS '状态';
COMMENT ON COLUMN prompt_templates.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN prompt_templates.updated_at IS '更新时间';
COMMENT ON COLUMN prompt_templates.version IS '版本号';
COMMENT ON TABLE resource_grants IS 'resource_grants表';
COMMENT ON COLUMN resource_grants.actions IS 'resource_grants actions';
COMMENT ON COLUMN resource_grants.created_at IS '创建时间';
COMMENT ON COLUMN resource_grants.grant_group_id IS '分配卡片分组 ID';
COMMENT ON COLUMN resource_grants.grant_group_name IS '分配卡片名称';
COMMENT ON COLUMN resource_grants.id IS '主键';
COMMENT ON COLUMN resource_grants.principal_id IS '授权主体 ID';
COMMENT ON COLUMN resource_grants.principal_type IS '授权主体类型';
COMMENT ON COLUMN resource_grants.resource_id IS '资源 ID';
COMMENT ON COLUMN resource_grants.resource_type IS '资源类型';
COMMENT ON COLUMN resource_grants.tenant_id IS '所属租户 ID';
COMMENT ON TABLE roles IS '角色表';
COMMENT ON COLUMN roles.built_in IS '是否为内置数据';
COMMENT ON COLUMN roles.code IS '编码';
COMMENT ON COLUMN roles.created_at IS '创建时间';
COMMENT ON COLUMN roles.description IS '描述';
COMMENT ON COLUMN roles.id IS '主键';
COMMENT ON COLUMN roles.name IS '名称';
COMMENT ON COLUMN roles.status IS '状态';
COMMENT ON COLUMN roles.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN roles.updated_at IS '更新时间';
COMMENT ON TABLE sensitive_action_policies IS 'sensitive_action_policies表';
COMMENT ON COLUMN sensitive_action_policies.action_code IS 'sensitive_action_policies action code';
COMMENT ON COLUMN sensitive_action_policies.audit_required IS 'sensitive_action_policies audit required';
COMMENT ON COLUMN sensitive_action_policies.created_at IS '创建时间';
COMMENT ON COLUMN sensitive_action_policies.id IS '主键';
COMMENT ON COLUMN sensitive_action_policies.requires_approval IS 'sensitive_action_policies requires approval';
COMMENT ON COLUMN sensitive_action_policies.requires_reauth IS 'sensitive_action_policies requires reauth';
COMMENT ON COLUMN sensitive_action_policies.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN sensitive_action_policies.updated_at IS '更新时间';
COMMENT ON TABLE system_capabilities IS '系统能力表';
COMMENT ON COLUMN system_capabilities.capability_type IS '系统能力 capability type';
COMMENT ON COLUMN system_capabilities.code IS '编码';
COMMENT ON COLUMN system_capabilities.config IS '配置 JSON';
COMMENT ON COLUMN system_capabilities.connectivity_status IS '系统能力 connectivity status';
COMMENT ON COLUMN system_capabilities.created_at IS '创建时间';
COMMENT ON COLUMN system_capabilities.description IS '描述';
COMMENT ON COLUMN system_capabilities.id IS '主键';
COMMENT ON COLUMN system_capabilities.name IS '名称';
COMMENT ON COLUMN system_capabilities.risk_level IS '风险等级';
COMMENT ON COLUMN system_capabilities.status IS '状态';
COMMENT ON COLUMN system_capabilities.updated_at IS '更新时间';
COMMENT ON COLUMN system_capabilities.version IS '版本号';
COMMENT ON TABLE tenant_asset_access_grants IS '租户能力成员授权表';
COMMENT ON COLUMN tenant_asset_access_grants.asset_id IS '能力资产 ID';
COMMENT ON COLUMN tenant_asset_access_grants.created_at IS '创建时间';
COMMENT ON COLUMN tenant_asset_access_grants.created_by IS '创建人用户 ID';
COMMENT ON COLUMN tenant_asset_access_grants.grantee_user_id IS '被授权用户 ID';
COMMENT ON COLUMN tenant_asset_access_grants.id IS '主键';
COMMENT ON COLUMN tenant_asset_access_grants.tenant_id IS '所属租户 ID';
COMMENT ON TABLE tenant_asset_capabilities IS '租户自建能力资产表';
COMMENT ON COLUMN tenant_asset_capabilities.asset_type IS '能力资产类型';
COMMENT ON COLUMN tenant_asset_capabilities.base_system_capability_id IS '派生的系统能力 ID';
COMMENT ON COLUMN tenant_asset_capabilities.code IS '编码';
COMMENT ON COLUMN tenant_asset_capabilities.config IS '配置 JSON';
COMMENT ON COLUMN tenant_asset_capabilities.created_at IS '创建时间';
COMMENT ON COLUMN tenant_asset_capabilities.created_by IS '创建人用户 ID';
COMMENT ON COLUMN tenant_asset_capabilities.description IS '描述';
COMMENT ON COLUMN tenant_asset_capabilities.edit_scope IS '内容编辑权限范围：self、specified、all';
COMMENT ON COLUMN tenant_asset_capabilities.id IS '主键';
COMMENT ON COLUMN tenant_asset_capabilities.name IS '名称';
COMMENT ON COLUMN tenant_asset_capabilities.published_at IS '发布时间';
COMMENT ON COLUMN tenant_asset_capabilities.read_scope IS '读取/使用权限范围：self、specified、all';
COMMENT ON COLUMN tenant_asset_capabilities.risk_level IS '风险等级';
COMMENT ON COLUMN tenant_asset_capabilities.source_type IS '资产来源：custom 自建、derived 派生';
COMMENT ON COLUMN tenant_asset_capabilities.status IS '状态';
COMMENT ON COLUMN tenant_asset_capabilities.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN tenant_asset_capabilities.updated_at IS '更新时间';
COMMENT ON COLUMN tenant_asset_capabilities.updated_by IS '更新人用户 ID';
COMMENT ON COLUMN tenant_asset_capabilities.version IS '版本号';
COMMENT ON TABLE tenant_capability_grants IS 'tenant_capability_grants表';
COMMENT ON COLUMN tenant_capability_grants.capability_id IS '系统能力 ID';
COMMENT ON COLUMN tenant_capability_grants.created_at IS '创建时间';
COMMENT ON COLUMN tenant_capability_grants.id IS '主键';
COMMENT ON COLUMN tenant_capability_grants.quota IS 'tenant_capability_grants quota';
COMMENT ON COLUMN tenant_capability_grants.status IS '状态';
COMMENT ON COLUMN tenant_capability_grants.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN tenant_capability_grants.updated_at IS '更新时间';
COMMENT ON TABLE tenant_model_assignments IS 'tenant_model_assignments表';
COMMENT ON COLUMN tenant_model_assignments.created_at IS '创建时间';
COMMENT ON COLUMN tenant_model_assignments.default_model IS 'tenant_model_assignments default model';
COMMENT ON COLUMN tenant_model_assignments.id IS '主键';
COMMENT ON COLUMN tenant_model_assignments.provider_id IS '模型供应商 ID';
COMMENT ON COLUMN tenant_model_assignments.settings IS 'tenant_model_assignments settings';
COMMENT ON COLUMN tenant_model_assignments.status IS '状态';
COMMENT ON COLUMN tenant_model_assignments.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN tenant_model_assignments.updated_at IS '更新时间';
COMMENT ON TABLE tenant_org_roles IS 'tenant_org_roles表';
COMMENT ON COLUMN tenant_org_roles.created_at IS '创建时间';
COMMENT ON COLUMN tenant_org_roles.description IS '描述';
COMMENT ON COLUMN tenant_org_roles.id IS '主键';
COMMENT ON COLUMN tenant_org_roles.is_system IS '是否为系统预置';
COMMENT ON COLUMN tenant_org_roles.name IS '名称';
COMMENT ON COLUMN tenant_org_roles.page_permissions IS '页签权限列表 JSON';
COMMENT ON COLUMN tenant_org_roles.resource_permissions IS 'tenant_org_roles resource permissions';
COMMENT ON COLUMN tenant_org_roles.status IS '状态';
COMMENT ON COLUMN tenant_org_roles.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN tenant_org_roles.updated_at IS '更新时间';
COMMENT ON TABLE tenant_sso_providers IS 'tenant_sso_providers表';
COMMENT ON COLUMN tenant_sso_providers.authorization_endpoint IS 'tenant_sso_providers authorization endpoint';
COMMENT ON COLUMN tenant_sso_providers.auto_bind_email IS 'tenant_sso_providers auto bind email';
COMMENT ON COLUMN tenant_sso_providers.client_id IS 'tenant_sso_providers client id';
COMMENT ON COLUMN tenant_sso_providers.config IS '配置 JSON';
COMMENT ON COLUMN tenant_sso_providers.created_at IS '创建时间';
COMMENT ON COLUMN tenant_sso_providers.email_domain IS 'tenant_sso_providers email domain';
COMMENT ON COLUMN tenant_sso_providers.encrypted_client_secret IS 'tenant_sso_providers encrypted client secret';
COMMENT ON COLUMN tenant_sso_providers.id IS '主键';
COMMENT ON COLUMN tenant_sso_providers.issuer IS 'tenant_sso_providers issuer';
COMMENT ON COLUMN tenant_sso_providers.jwks_uri IS 'tenant_sso_providers jwks uri';
COMMENT ON COLUMN tenant_sso_providers.logout_endpoint IS 'tenant_sso_providers logout endpoint';
COMMENT ON COLUMN tenant_sso_providers.name IS '名称';
COMMENT ON COLUMN tenant_sso_providers.provider_type IS 'tenant_sso_providers provider type';
COMMENT ON COLUMN tenant_sso_providers.status IS '状态';
COMMENT ON COLUMN tenant_sso_providers.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN tenant_sso_providers.token_endpoint IS 'tenant_sso_providers token endpoint';
COMMENT ON COLUMN tenant_sso_providers.updated_at IS '更新时间';
COMMENT ON TABLE tenants IS '租户表';
COMMENT ON COLUMN tenants.code IS '编码';
COMMENT ON COLUMN tenants.contact_email IS '租户 contact email';
COMMENT ON COLUMN tenants.contact_name IS '租户 contact name';
COMMENT ON COLUMN tenants.created_at IS '创建时间';
COMMENT ON COLUMN tenants.id IS '主键';
COMMENT ON COLUMN tenants.model_quota IS '租户 model quota';
COMMENT ON COLUMN tenants.name IS '名称';
COMMENT ON COLUMN tenants.settings IS '租户 settings';
COMMENT ON COLUMN tenants.status IS '状态';
COMMENT ON COLUMN tenants.updated_at IS '更新时间';
COMMENT ON TABLE user_external_identities IS 'user_external_identities表';
COMMENT ON COLUMN user_external_identities.created_at IS '创建时间';
COMMENT ON COLUMN user_external_identities.display_name IS 'user_external_identities display name';
COMMENT ON COLUMN user_external_identities.email IS 'user_external_identities email';
COMMENT ON COLUMN user_external_identities.id IS '主键';
COMMENT ON COLUMN user_external_identities.last_login_at IS 'user_external_identities last login at';
COMMENT ON COLUMN user_external_identities.provider_id IS '模型供应商 ID';
COMMENT ON COLUMN user_external_identities.subject IS 'user_external_identities subject';
COMMENT ON COLUMN user_external_identities.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN user_external_identities.updated_at IS '更新时间';
COMMENT ON COLUMN user_external_identities.user_id IS '用户 ID';
COMMENT ON TABLE user_membership_roles IS 'user_membership_roles表';
COMMENT ON COLUMN user_membership_roles.created_at IS '创建时间';
COMMENT ON COLUMN user_membership_roles.id IS '主键';
COMMENT ON COLUMN user_membership_roles.membership_id IS '租户成员关系 ID';
COMMENT ON COLUMN user_membership_roles.role_id IS '角色 ID';
COMMENT ON COLUMN user_membership_roles.status IS '状态';
COMMENT ON COLUMN user_membership_roles.updated_at IS '更新时间';
COMMENT ON TABLE user_memberships IS 'user_memberships表';
COMMENT ON COLUMN user_memberships.created_at IS '创建时间';
COMMENT ON COLUMN user_memberships.department_id IS '部门 ID';
COMMENT ON COLUMN user_memberships.id IS '主键';
COMMENT ON COLUMN user_memberships.is_default IS '是否为默认项';
COMMENT ON COLUMN user_memberships.status IS '状态';
COMMENT ON COLUMN user_memberships.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN user_memberships.user_id IS '用户 ID';
COMMENT ON TABLE user_role_assignments IS '用户登录入口角色分配表';
COMMENT ON COLUMN user_role_assignments.created_at IS '创建时间';
COMMENT ON COLUMN user_role_assignments.id IS '主键';
COMMENT ON COLUMN user_role_assignments.is_default IS '是否为默认项';
COMMENT ON COLUMN user_role_assignments.label IS '展示标签';
COMMENT ON COLUMN user_role_assignments.role IS '系统登录入口角色：business、tenant_admin、system_admin';
COMMENT ON COLUMN user_role_assignments.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN user_role_assignments.user_id IS '用户 ID';
COMMENT ON TABLE users IS '用户表';
COMMENT ON COLUMN users.avatar_url IS '用户 avatar url';
COMMENT ON COLUMN users.created_at IS '创建时间';
COMMENT ON COLUMN users.display_name IS '用户 display name';
COMMENT ON COLUMN users.email IS '用户 email';
COMMENT ON COLUMN users.id IS '主键';
COMMENT ON COLUMN users.last_login_at IS '用户 last login at';
COMMENT ON COLUMN users.locale IS '用户 locale';
COMMENT ON COLUMN users.password_hash IS '用户 password hash';
COMMENT ON COLUMN users.phone IS '用户 phone';
COMMENT ON COLUMN users.status IS '状态';
COMMENT ON COLUMN users.updated_at IS '更新时间';
COMMENT ON COLUMN users.username IS '用户 username';
COMMENT ON TABLE variable_snapshots IS 'variable_snapshots表';
COMMENT ON COLUMN variable_snapshots.created_at IS '创建时间';
COMMENT ON COLUMN variable_snapshots.delivery_visible IS 'variable_snapshots delivery visible';
COMMENT ON COLUMN variable_snapshots.id IS '主键';
COMMENT ON COLUMN variable_snapshots.node_run_id IS '节点运行记录 ID';
COMMENT ON COLUMN variable_snapshots.run_id IS '工作流运行实例 ID';
COMMENT ON COLUMN variable_snapshots.sensitive IS 'variable_snapshots sensitive';
COMMENT ON COLUMN variable_snapshots.source_node_key IS 'variable_snapshots source node key';
COMMENT ON COLUMN variable_snapshots.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN variable_snapshots.value_snapshot IS 'variable_snapshots value snapshot';
COMMENT ON COLUMN variable_snapshots.value_type IS 'variable_snapshots value type';
COMMENT ON COLUMN variable_snapshots.variable_name IS 'variable_snapshots variable name';
COMMENT ON COLUMN variable_snapshots.workflow_id IS '工作流定义 ID';
COMMENT ON COLUMN variable_snapshots.workflow_version_id IS '工作流发布版本 ID';
COMMENT ON TABLE workflow_access_grants IS '工作流成员授权表';
COMMENT ON COLUMN workflow_access_grants.access_level IS '授权级别：read 或 edit';
COMMENT ON COLUMN workflow_access_grants.created_at IS '创建时间';
COMMENT ON COLUMN workflow_access_grants.created_by IS '创建人用户 ID';
COMMENT ON COLUMN workflow_access_grants.grantee_user_id IS '被授权用户 ID';
COMMENT ON COLUMN workflow_access_grants.id IS '主键';
COMMENT ON COLUMN workflow_access_grants.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN workflow_access_grants.workflow_id IS '工作流定义 ID';
COMMENT ON TABLE workflow_cluster_agent_runs IS 'workflow_cluster_agent_runs表';
COMMENT ON COLUMN workflow_cluster_agent_runs.agent_index IS 'workflow_cluster_agent_runs agent index';
COMMENT ON COLUMN workflow_cluster_agent_runs.completed_at IS '完成时间';
COMMENT ON COLUMN workflow_cluster_agent_runs.error_code IS '错误码';
COMMENT ON COLUMN workflow_cluster_agent_runs.error_message IS '错误信息';
COMMENT ON COLUMN workflow_cluster_agent_runs.id IS '主键';
COMMENT ON COLUMN workflow_cluster_agent_runs.name IS '名称';
COMMENT ON COLUMN workflow_cluster_agent_runs.node_run_id IS '节点运行记录 ID';
COMMENT ON COLUMN workflow_cluster_agent_runs.output IS 'workflow_cluster_agent_runs output';
COMMENT ON COLUMN workflow_cluster_agent_runs.run_id IS '工作流运行实例 ID';
COMMENT ON COLUMN workflow_cluster_agent_runs.started_at IS '开始时间';
COMMENT ON COLUMN workflow_cluster_agent_runs.status IS '状态';
COMMENT ON COLUMN workflow_cluster_agent_runs.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN workflow_cluster_agent_runs.updated_at IS '更新时间';
COMMENT ON TABLE workflow_definitions IS '工作流定义表';
COMMENT ON COLUMN workflow_definitions.created_at IS '创建时间';
COMMENT ON COLUMN workflow_definitions.created_by IS '创建人用户 ID';
COMMENT ON COLUMN workflow_definitions.description IS '描述';
COMMENT ON COLUMN workflow_definitions.id IS '主键';
COMMENT ON COLUMN workflow_definitions.launch_enabled IS '业务入口是否允许发起';
COMMENT ON COLUMN workflow_definitions.name IS '名称';
COMMENT ON COLUMN workflow_definitions.node_count IS '节点数量';
COMMENT ON COLUMN workflow_definitions.read_scope IS '读取/使用权限范围：self、specified、all';
COMMENT ON COLUMN workflow_definitions.status IS '状态';
COMMENT ON COLUMN workflow_definitions.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN workflow_definitions.updated_at IS '更新时间';
COMMENT ON COLUMN workflow_definitions.updated_by IS '更新人用户 ID';
COMMENT ON TABLE workflow_edge_definitions IS 'workflow_edge_definitions表';
COMMENT ON COLUMN workflow_edge_definitions.condition_expression IS 'workflow_edge_definitions condition expression';
COMMENT ON COLUMN workflow_edge_definitions.created_at IS '创建时间';
COMMENT ON COLUMN workflow_edge_definitions.edge_key IS 'workflow_edge_definitions edge key';
COMMENT ON COLUMN workflow_edge_definitions.id IS '主键';
COMMENT ON COLUMN workflow_edge_definitions.label IS '展示标签';
COMMENT ON COLUMN workflow_edge_definitions.sort_order IS 'workflow_edge_definitions sort order';
COMMENT ON COLUMN workflow_edge_definitions.source_node_key IS 'workflow_edge_definitions source node key';
COMMENT ON COLUMN workflow_edge_definitions.target_node_key IS 'workflow_edge_definitions target node key';
COMMENT ON COLUMN workflow_edge_definitions.updated_at IS '更新时间';
COMMENT ON COLUMN workflow_edge_definitions.workflow_id IS '工作流定义 ID';
COMMENT ON TABLE workflow_node_definitions IS 'workflow_node_definitions表';
COMMENT ON COLUMN workflow_node_definitions.config IS '配置 JSON';
COMMENT ON COLUMN workflow_node_definitions.created_at IS '创建时间';
COMMENT ON COLUMN workflow_node_definitions.id IS '主键';
COMMENT ON COLUMN workflow_node_definitions.input_variables IS 'workflow_node_definitions input variables';
COMMENT ON COLUMN workflow_node_definitions.name IS '名称';
COMMENT ON COLUMN workflow_node_definitions.node_key IS 'workflow_node_definitions node key';
COMMENT ON COLUMN workflow_node_definitions.node_type IS 'workflow_node_definitions node type';
COMMENT ON COLUMN workflow_node_definitions.output_variables IS 'workflow_node_definitions output variables';
COMMENT ON COLUMN workflow_node_definitions.position_x IS 'workflow_node_definitions position x';
COMMENT ON COLUMN workflow_node_definitions.position_y IS 'workflow_node_definitions position y';
COMMENT ON COLUMN workflow_node_definitions.sort_order IS 'workflow_node_definitions sort order';
COMMENT ON COLUMN workflow_node_definitions.updated_at IS '更新时间';
COMMENT ON COLUMN workflow_node_definitions.workflow_id IS '工作流定义 ID';
COMMENT ON TABLE workflow_node_runs IS '工作流节点运行表';
COMMENT ON COLUMN workflow_node_runs.completed_at IS '完成时间';
COMMENT ON COLUMN workflow_node_runs.config_snapshot IS '工作流节点运行 config snapshot';
COMMENT ON COLUMN workflow_node_runs.id IS '主键';
COMMENT ON COLUMN workflow_node_runs.input_snapshot IS '工作流节点运行 input snapshot';
COMMENT ON COLUMN workflow_node_runs.name IS '名称';
COMMENT ON COLUMN workflow_node_runs.node_key IS '工作流节点运行 node key';
COMMENT ON COLUMN workflow_node_runs.node_type IS '工作流节点运行 node type';
COMMENT ON COLUMN workflow_node_runs.output_snapshot IS '工作流节点运行 output snapshot';
COMMENT ON COLUMN workflow_node_runs.run_id IS '工作流运行实例 ID';
COMMENT ON COLUMN workflow_node_runs.sort_order IS '工作流节点运行 sort order';
COMMENT ON COLUMN workflow_node_runs.started_at IS '开始时间';
COMMENT ON COLUMN workflow_node_runs.state IS '工作流节点运行 state';
COMMENT ON COLUMN workflow_node_runs.state_label IS '工作流节点运行 state label';
COMMENT ON COLUMN workflow_node_runs.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN workflow_node_runs.updated_at IS '更新时间';
COMMENT ON COLUMN workflow_node_runs.workflow_id IS '工作流定义 ID';
COMMENT ON COLUMN workflow_node_runs.workflow_version_id IS '工作流发布版本 ID';
COMMENT ON TABLE workflow_run_events IS 'workflow_run_events表';
COMMENT ON COLUMN workflow_run_events.description IS '描述';
COMMENT ON COLUMN workflow_run_events.event_time IS 'workflow_run_events event time';
COMMENT ON COLUMN workflow_run_events.event_type IS 'workflow_run_events event type';
COMMENT ON COLUMN workflow_run_events.id IS '主键';
COMMENT ON COLUMN workflow_run_events.node_key IS 'workflow_run_events node key';
COMMENT ON COLUMN workflow_run_events.operator_id IS 'workflow_run_events operator id';
COMMENT ON COLUMN workflow_run_events.payload IS '载荷 JSON';
COMMENT ON COLUMN workflow_run_events.run_id IS '工作流运行实例 ID';
COMMENT ON COLUMN workflow_run_events.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN workflow_run_events.title IS 'workflow_run_events title';
COMMENT ON TABLE workflow_run_execution_jobs IS 'workflow_run_execution_jobs表';
COMMENT ON COLUMN workflow_run_execution_jobs.attempt IS 'workflow_run_execution_jobs attempt';
COMMENT ON COLUMN workflow_run_execution_jobs.deadline_at IS 'workflow_run_execution_jobs deadline at';
COMMENT ON COLUMN workflow_run_execution_jobs.enqueued_at IS 'workflow_run_execution_jobs enqueued at';
COMMENT ON COLUMN workflow_run_execution_jobs.error_code IS '错误码';
COMMENT ON COLUMN workflow_run_execution_jobs.error_message IS '错误信息';
COMMENT ON COLUMN workflow_run_execution_jobs.finished_at IS 'workflow_run_execution_jobs finished at';
COMMENT ON COLUMN workflow_run_execution_jobs.id IS '主键';
COMMENT ON COLUMN workflow_run_execution_jobs.idempotency_key IS 'workflow_run_execution_jobs idempotency key';
COMMENT ON COLUMN workflow_run_execution_jobs.node_run_id IS '节点运行记录 ID';
COMMENT ON COLUMN workflow_run_execution_jobs.operator_id IS 'workflow_run_execution_jobs operator id';
COMMENT ON COLUMN workflow_run_execution_jobs.request_id IS 'workflow_run_execution_jobs request id';
COMMENT ON COLUMN workflow_run_execution_jobs.run_id IS '工作流运行实例 ID';
COMMENT ON COLUMN workflow_run_execution_jobs.started_at IS '开始时间';
COMMENT ON COLUMN workflow_run_execution_jobs.status IS '状态';
COMMENT ON COLUMN workflow_run_execution_jobs.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN workflow_run_execution_jobs.updated_at IS '更新时间';
COMMENT ON COLUMN workflow_run_execution_jobs.worker_id IS 'workflow_run_execution_jobs worker id';
COMMENT ON TABLE workflow_runs IS '工作流运行实例表';
COMMENT ON COLUMN workflow_runs.completed_at IS '完成时间';
COMMENT ON COLUMN workflow_runs.completed_node_count IS '工作流运行实例 completed node count';
COMMENT ON COLUMN workflow_runs.created_by IS '创建人用户 ID';
COMMENT ON COLUMN workflow_runs.current_node_key IS '工作流运行实例 current node key';
COMMENT ON COLUMN workflow_runs.current_node_name IS '工作流运行实例 current node name';
COMMENT ON COLUMN workflow_runs.current_node_type IS '工作流运行实例 current node type';
COMMENT ON COLUMN workflow_runs.id IS '主键';
COMMENT ON COLUMN workflow_runs.progress_percent IS '工作流运行实例 progress percent';
COMMENT ON COLUMN workflow_runs.saved IS '工作流运行实例 saved';
COMMENT ON COLUMN workflow_runs.started_at IS '开始时间';
COMMENT ON COLUMN workflow_runs.state IS '工作流运行实例 state';
COMMENT ON COLUMN workflow_runs.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN workflow_runs.title IS '工作流运行实例 title';
COMMENT ON COLUMN workflow_runs.total_node_count IS '工作流运行实例 total node count';
COMMENT ON COLUMN workflow_runs.updated_at IS '更新时间';
COMMENT ON COLUMN workflow_runs.workflow_id IS '工作流定义 ID';
COMMENT ON COLUMN workflow_runs.workflow_name IS '工作流运行实例 workflow name';
COMMENT ON COLUMN workflow_runs.workflow_version_id IS '工作流发布版本 ID';
COMMENT ON COLUMN workflow_runs.workflow_version_number IS '工作流运行实例 workflow version number';
COMMENT ON TABLE workflow_variable_definitions IS 'workflow_variable_definitions表';
COMMENT ON COLUMN workflow_variable_definitions.created_at IS '创建时间';
COMMENT ON COLUMN workflow_variable_definitions.deliverable IS 'workflow_variable_definitions deliverable';
COMMENT ON COLUMN workflow_variable_definitions.description IS '描述';
COMMENT ON COLUMN workflow_variable_definitions.id IS '主键';
COMMENT ON COLUMN workflow_variable_definitions.json_schema IS 'workflow_variable_definitions json schema';
COMMENT ON COLUMN workflow_variable_definitions.sensitive IS 'workflow_variable_definitions sensitive';
COMMENT ON COLUMN workflow_variable_definitions.sort_order IS 'workflow_variable_definitions sort order';
COMMENT ON COLUMN workflow_variable_definitions.source_node_key IS 'workflow_variable_definitions source node key';
COMMENT ON COLUMN workflow_variable_definitions.updated_at IS '更新时间';
COMMENT ON COLUMN workflow_variable_definitions.variable_key IS 'workflow_variable_definitions variable key';
COMMENT ON COLUMN workflow_variable_definitions.variable_type IS 'workflow_variable_definitions variable type';
COMMENT ON COLUMN workflow_variable_definitions.workflow_id IS '工作流定义 ID';
COMMENT ON TABLE workflow_versions IS '工作流发布版本表';
COMMENT ON COLUMN workflow_versions.definition_snapshot IS '工作流发布版本 definition snapshot';
COMMENT ON COLUMN workflow_versions.id IS '主键';
COMMENT ON COLUMN workflow_versions.node_count IS '节点数量';
COMMENT ON COLUMN workflow_versions.published_at IS '发布时间';
COMMENT ON COLUMN workflow_versions.published_by IS '发布人用户 ID';
COMMENT ON COLUMN workflow_versions.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN workflow_versions.version_number IS '版本序号';
COMMENT ON COLUMN workflow_versions.workflow_id IS '工作流定义 ID';
COMMENT ON TABLE workflow_waiting_events IS 'workflow_waiting_events表';
COMMENT ON COLUMN workflow_waiting_events.action_type IS 'workflow_waiting_events action type';
COMMENT ON COLUMN workflow_waiting_events.created_at IS '创建时间';
COMMENT ON COLUMN workflow_waiting_events.id IS '主键';
COMMENT ON COLUMN workflow_waiting_events.node_key IS 'workflow_waiting_events node key';
COMMENT ON COLUMN workflow_waiting_events.node_run_id IS '节点运行记录 ID';
COMMENT ON COLUMN workflow_waiting_events.payload IS '载荷 JSON';
COMMENT ON COLUMN workflow_waiting_events.resolved_at IS 'workflow_waiting_events resolved at';
COMMENT ON COLUMN workflow_waiting_events.resolved_by IS 'workflow_waiting_events resolved by';
COMMENT ON COLUMN workflow_waiting_events.run_id IS '工作流运行实例 ID';
COMMENT ON COLUMN workflow_waiting_events.status IS '状态';
COMMENT ON COLUMN workflow_waiting_events.tenant_id IS '所属租户 ID';
COMMENT ON COLUMN workflow_waiting_events.title IS 'workflow_waiting_events title';
COMMENT ON COLUMN workflow_waiting_events.waiting_for_id IS 'workflow_waiting_events waiting for id';
COMMENT ON COLUMN workflow_waiting_events.waiting_for_type IS 'workflow_waiting_events waiting for type';
COMMENT ON COLUMN workflow_waiting_events.waiting_reason IS 'workflow_waiting_events waiting reason';
COMMENT ON COLUMN workflow_waiting_events.workflow_id IS '工作流定义 ID';
