spring:
  application:
    name: agentum-api
  profiles:
    active: local

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  pattern:
    level: "%5p [requestId:%X{requestId:-none}]"
